Repository CMPUT301W24T26/OOPs-I-Pushed-To-Main, pull requests merged in 2024-04, with the labels that each got.

#157 Ningze part4 event
  src/OOPsIPushedToMain/app/build.gradle.kts
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/Database/FirebaseAccess.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/Event.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/EventDetailsActivity.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/EventListActivity.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/FirestoreEventUtils.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/NewEventActivity.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/ProfileActivity.java
  src/OOPsIPushedToMain/app/src/main/res/menu/event_sort_menu.xml
Labels: event

#161 Justin qr code rewrite
  src/OOPsIPushedToMain/app/src/androidTest/java/com/oopsipushedtomain/QRCodeUnitTest.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/Database/FirebaseAccess.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/Event.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/EventDetailsActivity.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/QRCode.java
Labels: model

#162 Finished refactoring ProfileActivity
  src/OOPsIPushedToMain/app/src/main/AndroidManifest.xml
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/Database/FirebaseAccess.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/DialogInputListeners/CustomDatePickerDialog.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/DialogInputListeners/DialogInputListener.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/DialogInputListeners/InputTextDialog.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/DialogInputListeners/PhonePickerDialog.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/ProfileActivity.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/User.java
Labels: bug

#164 Small Bug: Updated the logic for the geolocation toggle
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/ProfileActivity.java
Labels: bug

#169 Updated QR Scanning to support the multiple types of QR codes
  src/OOPsIPushedToMain/app/build.gradle.kts
  src/OOPsIPushedToMain/app/src/androidTest/java/com/oopsipushedtomain/UserUnitTest.java
  src/OOPsIPushedToMain/app/src/main/AndroidManifest.xml
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/Database/FirebaseAccess.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/EventDetailsActivity.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/ProfileActivity.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/QRCode.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/ShowImageFragment.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/User.java
  src/OOPsIPushedToMain/app/src/main/res/drawable/admin_code.jpg
  src/OOPsIPushedToMain/app/src/main/res/layout/activity_event_details.xml
  src/OOPsIPushedToMain/app/src/main/res/layout/fragment_show_image.xml
  src/OOPsIPushedToMain/app/src/main/res/xml/file_paths.xml
Labels: admin, organizer

#170 change ShowImageFragment to ShowImageActivity
  src/OOPsIPushedToMain/app/src/main/AndroidManifest.xml
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/Event.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/EventDetailsActivity.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/ShowImageActivity.java
  src/OOPsIPushedToMain/app/src/main/java/com/oopsipushedtomain/ShowImageFragment.java
  src/OOPsIPushedToMain/app/src/main/res/layout/activity_show_image.xml
  src/OOPsIPushedToMain/app/src/main/res/layout/activity_view_limit_attendees.xml
Labels: model

#186 Justin qr code rewrite
  src/OOPsIPushedToMain/app/src/androidTest/java/com/oopsipushedtomain/QRCodeIntentTest.java
Labels: model

#198 Uml final update
  doc/UML-Diagram-Final.drawio
Labels: documentation
